import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next on every build and is gitignored.
    ignores: [
      '.next/**',
      'node_modules/**',
      'drizzle/**',
      'spec/generated/**',
      'coverage/**',
      'dist/**',
      'next-env.d.ts',
    ],
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },
  {
    // ---------------------------------------------------------------------
    // E21-09 / E21-10: money and date discipline.
    //
    // Firefly III returns monetary amounts as STRINGS to preserve precision,
    // and dates without a reliable local-time meaning. Coercing either with a
    // built-in is how you get cent-level drift and off-by-one-day reports.
    // Everything must go through lib/money.ts and lib/date.ts.
    // ---------------------------------------------------------------------
    files: ['app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}', 'server/**/*.ts'],
    rules: {
      'no-restricted-globals': [
        'error',
        {
          name: 'parseFloat',
          message: 'Money is a string until rendered. Use lib/money.ts (decimal.js).',
        },
        {
          name: 'parseInt',
          message: 'Use Number.parseInt explicitly, or lib/money.ts for monetary values.',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length>0]",
          message:
            'Never parse a date in implicit local time. Use lib/date.ts (parseFireflyDate / parseFireflyDateTime).',
        },
        {
          selector: "CallExpression[callee.name='Number'][arguments.length>0]",
          message:
            'Do not coerce Firefly amounts with Number(). Use lib/money.ts (toDecimal / add / formatMoney).',
        },
      ],
    },
  },
  {
    // The shared modules are the one place these primitives are allowed.
    files: ['lib/money.ts', 'lib/date.ts', 'lib/env.ts', '**/*.test.ts', 'scripts/**/*.ts'],
    rules: {
      'no-restricted-globals': 'off',
      'no-restricted-syntax': 'off',
    },
  },
];

export default eslintConfig;
