import { build } from 'esbuild';

/**
 * Bundle the migration runner into a single CommonJS file so the production
 * image can apply migrations with plain `node`, without tsx, TypeScript, or
 * path-alias resolution at runtime.
 */
async function main() {
  await build({
    entryPoints: ['server/db/migrate.ts'],
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    outfile: 'dist/migrate.cjs',
    // pg ships an optional native binding; keep it external.
    external: ['pg-native'],
    banner: { js: '// Generated by scripts/build-migrator.ts — do not edit.' },
    logLevel: 'info',
  });
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
