import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';

/**
 * Bundle the command-line tools the production image needs into plain CommonJS,
 * so they run with `node dist/<name>.cjs` and nothing else.
 *
 * This exists because the runtime image is a Next.js standalone build: it has
 * `node_modules` and a server, but no `scripts/`, no TypeScript, no tsx and no
 * package manager — and it runs as a non-root user who cannot write to /app, so
 * `pnpm` cannot even bootstrap itself. Anything an operator has to run inside
 * the container has to arrive already built.
 */

// `server-only` throws on import outside a React Server Component build. It is
// doing its job — the modules that carry it hold the token-sealing key
// derivation — but a CLI is a legitimate server caller, so the marker is
// satisfied with an empty module rather than bypassed.
mkdirSync('dist', { recursive: true });
writeFileSync('dist/.server-only-shim.js', 'module.exports = {};\n');

const TARGETS = [
  { entry: 'server/db/migrate.ts', out: 'dist/migrate.cjs' },
  { entry: 'scripts/demo-seed.ts', out: 'dist/demo-seed.cjs' },
  { entry: 'scripts/demo-account.ts', out: 'dist/demo-account.cjs' },
  // The admin-role escape hatch. It has to be here rather than in `scripts/`
  // alone, because the case it exists for — an instance with no administrator —
  // is one an operator can only fix from inside the running container.
  { entry: 'scripts/user-admin.ts', out: 'dist/user-admin.cjs' },
];

async function main() {
  for (const target of TARGETS) {
    await build({
      entryPoints: [target.entry],
      bundle: true,
      platform: 'node',
      target: 'node20',
      format: 'cjs',
      outfile: target.out,
      alias: { 'server-only': './dist/.server-only-shim.js' },
      // Native bindings stay external: they are already in the image's
      // node_modules, and bundling a .node file is not a thing.
      external: ['pg-native', '@node-rs/argon2'],
      banner: { js: `// Generated by scripts/build-cli.ts — do not edit.` },
      logLevel: 'warning',
    });
    console.log(`  ${target.entry} → ${target.out}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
